Repository sigstore/sigstore-java, pull requests merged in 2023-02, with the labels that each got.

#302 Support Java toolchains in Gradle plugin
  sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/tasks/SigstoreSignFilesTask.kt
Labels: safe to test

#328 Add backoff on 429
  sigstore-java/build.gradle.kts
  sigstore-java/src/main/java/dev/sigstore/http/HttpClients.java
  sigstore-java/src/main/java/dev/sigstore/http/UnsuccessfulResponseHandler.java
  sigstore-java/src/test/java/dev/sigstore/http/UnsuccessfulResponseHandlerTest.java
Labels: safe to test

#334 Create CHANGELOG.md
  CHANGELOG.md
Labels: safe to test

#333 Fix reference to GitHub repo in release notes
  .github/workflows/tag-and-build-release.yaml
Labels: safe to test

#336 Update tag-and-build-release.yaml
  .github/workflows/tag-and-build-release.yaml
Labels: safe to test

#343 Add auto oidc selector
  sigstore-conformance/src/main/java/dev/sigstore/conformance/Main.java
  sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/tasks/SigstoreSignFilesTask.kt
  sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/work/SignWorkAction.kt
  sigstore-java/src/main/java/dev/sigstore/KeylessSigner.java
  sigstore-java/src/main/java/dev/sigstore/oidc/client/GithubActionsOidcClient.java
  sigstore-java/src/main/java/dev/sigstore/oidc/client/OidcClient.java
  sigstore-java/src/main/java/dev/sigstore/oidc/client/OidcClients.java
  sigstore-java/src/main/java/dev/sigstore/oidc/client/WebOidcClient.java
  sigstore-java/src/test/java/dev/sigstore/KeylessTest.java
Labels: safe to test

#344 Add all env to forked sigstore-java process
  sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/tasks/SigstoreSignFilesTask.kt
Labels: safe to test

#352 chore: reduce Renovate frequency, add labels for Renovate PRs
  renovate.json
Labels: safe to test, chore

#355 Update renovate.json
  renovate.json
Labels: safe to test

#351 test: distinguish between locally installed 0.3 and remote 0.3 sigstore-java better
  gradle.properties
  sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/SigstoreSignExtension.kt
  sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/work/SignWorkAction.kt
  sigstore-java/src/main/java/dev/sigstore/KeylessSigner.java
  sigstore-testkit/src/main/kotlin/dev/sigstore/testkit/BaseGradleTest.kt
  sigstore-testkit/src/main/kotlin/dev/sigstore/testkit/TestedSigstoreJava.kt
Labels: safe to test, chore

#356 chore: use protobuf-bom to align com.google.protobuf dependencies
  sigstore-java/build.gradle.kts
Labels: safe to test, dependencies, chore
